const SearchKeywords = [
	"Intern Software Developer",
	"Entry Level Software Developer",
	"Mid Level Software Developer",
	"Senior Level Software Developer",
	"Director Software Developer",
	"Executive Software Developer",
	"Associate Software Developer",
	"Data Scientist",
	"Data Analyst",
	"Data Engineer",
	"Data Architect",
	"Data Modeler",
	"Data Administrator",
	"Data Security Analyst",
	"Product Manager",
	"Product Owner",
	"Product Analyst",
	"Product Marketing Manager",
	"Product Designer",
	"Product Developer",
	"Product Engineer",
	"Product Architect",
	"Product Administrator",
	"Product Security Analyst",
	"Project Manager",
	"Project Owner",
	"Project Analyst",
	"Project Marketing Manager",
	"Project Designer",
	"UX Designer",
	"UI Designer",
	"Front End Developer",
	"Back End Developer",
	"Full Stack Developer",
	"Software Engineer",
	"Software Architect",
	"Software Administrator",
	"Software Security Analyst",
	"Software Developer",
	"Software Development Engineer",
	"Software Development Manager",
	"Software Development Director",
	"Software Development Executive",
	"Software Development Associate",
	"Software Development Intern",
	"Software Development Entry Level",
	"Software Development Mid Level",
	"Software Development Senior Level",
	"Human Resources Manager",
	"Human Resources Director",
	"Human Resources Executive",
	"Human Resources Associate",
	"Human Resources Intern",
	"Human Resources Entry Level",
	"Human Resources Mid Level",
	"Human Resources Senior Level",
	"Human Resources Analyst",
	"Financial Analyst",
	"Financial Manager",
	"Financial Director",
	"Financial Executive",
	"Financial Associate",
	"Financial Intern",
	"Financial Entry Level",
	"Financial Mid Level",
	"Financial Senior Level",
	"Accountant",
	"Accounting Manager",
	"Accounting Director",
	"Accounting Executive",
	"Accounting Associate",
	"Accounting Intern",
	"Accounting Entry Level",
	"Accounting Mid Level",
	"Accounting Senior Level",
	"Marketing Manager",
	"Marketing Director",
	"Marketing Executive",
	"Marketing Associate",
	"Marketing Intern",
	"Marketing Entry Level",
	"Marketing Mid Level",
	"Marketing Senior Level",
	"Sales Representative",
	"Sales Manager",
	"Sales Director",
	"Sales Executive",
	"Sales Associate",
	"Sales Intern",
	"Sales Entry Level",
	"Sales Mid Level",
	"Sales Senior Level",
	"Customer Service Representative",
	"Customer Service Manager",
	"Customer Service Director",
	"Customer Service Executive",
	"Customer Service Associate",
	"Customer Service Intern",
	"Customer Service Entry Level",
	"Customer Service Mid Level",
	"Customer Service Senior Level",
	"Customer Service Analyst",
	"Customer Service Specialist",
	"Customer Service Coordinator",
	"Operations Manager",
	"Operations Director",
	"Operations Executive",
	"Operations Associate",
	"Operations Intern",
	"Operations Entry Level",
	"Operations Mid Level",
	"Operations Senior Level",
	"Operations Analyst",
];

export default SearchKeywords;
